language: node_js
node_js:
- '0.10'
before_install: bundle install
before_script:
- npm install -g bower grunt-cli
- npm install
- bower install
script:
- grunt test
- grunt build
after_success:
- grunt docs:deploy:travis
before_deploy:
- grunt build
env:
  global:
    secure: GHo9ZJMLP2CvyuL5OktQINfBzNgFJJar+4t1HSuiPAlgecn1s0pCEFBaYo3Tuw9WGJkbeftFK5V1q7ftUHuXHbehH49eSwI74SSiSY+YEqC/BxBfQIlCvfzjYFrTKzN5G8Jj4IjZ9llAFx2C/CWxMdr61ahFJnX/tywddG1cbZIiVCDNjiu6IuTUu2R/BbyMZSahY6wZYf+YbP83XVy+4Q8mkozzQfel6qL1fpRsJCnyW7emIJwUmp5y0962coD6Gbo7BsvdJllcPa1nJ4J6EUtkZSCpX51xJZafJeh7iLDHpMcqdC5wlih4nO6xC7Mxvk+k1+ddCU6gcEP09K5RsJP4qH3nt+rrKDjL60EzoMTE94v4t0bKinoZm6Z0NsZzpfT0dH69fAOBPZI457Qq9sSn++AZZMyjQfxD/DOS7M7DPnia52RZXUmj6wqw3UojPIECUtjT+06LZkZ6HX9IJQ55y/OXcT1My1j7NyFIh/nrYR8Vdnt2eq6tMcBoUniIyPE8XpPmQZuwk1D85jwRjQY/93DEfKo0TJw989YqHOHy9QIUODGg/k+n9VmgBPf35SfQtMOyBFOHScEcXkQip08EsZyrU/sea/q3E5ytBO82AIVlJy6RkFh7gCoSmg6/SrpC38wkXQwMOQFb0fxvbtyI9u9U5EW8cg/Z8ftU0+o=
deploy:
  provider: s3
  access_key_id: AKIAIP5UVN77EFW7SUYA
  secret_access_key:
    secure: EV6BVRH1pj7vfIUmRiCZk4KNo8Lh5nrNuES2ppkOoxtjDT4LKuIyn7Q95UZhTEPZ+sTHk18ogtiDE6+MAxvTR3SG3NB4viGuLT4++Y2fk5FlotItSoPqr0nLJUooFUJoBS65hB2SKV4TpdE7ijVZQxPZEXBpJoffb7CXhEZunO5GPMdK2kjHSeSmhn5/sKx7i4hsVcKwAvp2w+4ElukA4lwD5cLVhXMQDj44uLHG9U60nFgYhou7OsGV5CN9nY1Wa1IH0l+0gzgiuAtLScOhYVRrfAoosc567kKRMN5YG95F2wgYNfIrkxH3nDh2JDDIIADYV7Jqn36Wg2wROPFUVs9V887ckHE0X49979cnGRFLh3iPEbYyMUFWFQrRGEaZ/wBA944YPMtCX1hVAe+/0M1xUtD+NMHZ5gYi04ISo76063zUr39PtxSEQD7VSQ5DFjtXF6E0UcXRMLeN1VI7tPXB28CmbynJ2lrgivVnLxjsNIS39o+2m7u0e5x9r7v+viXPIN4iX8j/RuyRGk9/Hd79Gi0Uyt7C2EKF3ZYMZXAXVkhRUMid6pfVJC1hjhcEQtlk3uZBj+/9zvUMtwx4CVGZpNiRpj6sh/ghSMoOPh+TEgsE3L+eoavRO5B9YeIcS4AT/R6pMEX0IjbAYveZopc+SFX7F8iZEMk0X+pPYo4=
  bucket: old-fashioned
  local-dir: dist
  acl: public_read
  skip_cleanup: true
  on:
    repo: myles/old-fashioned
