language: node_js
before_install: bundle install
before_script:
- npm install -g bower grunt-cli
script:
- npm test
before_deploy:
- npm run build
env:
  global:
    secure: GHo9ZJMLP2CvyuL5OktQINfBzNgFJJar+4t1HSuiPAlgecn1s0pCEFBaYo3Tuw9WGJkbeftFK5V1q7ftUHuXHbehH49eSwI74SSiSY+YEqC/BxBfQIlCvfzjYFrTKzN5G8Jj4IjZ9llAFx2C/CWxMdr61ahFJnX/tywddG1cbZIiVCDNjiu6IuTUu2R/BbyMZSahY6wZYf+YbP83XVy+4Q8mkozzQfel6qL1fpRsJCnyW7emIJwUmp5y0962coD6Gbo7BsvdJllcPa1nJ4J6EUtkZSCpX51xJZafJeh7iLDHpMcqdC5wlih4nO6xC7Mxvk+k1+ddCU6gcEP09K5RsJP4qH3nt+rrKDjL60EzoMTE94v4t0bKinoZm6Z0NsZzpfT0dH69fAOBPZI457Qq9sSn++AZZMyjQfxD/DOS7M7DPnia52RZXUmj6wqw3UojPIECUtjT+06LZkZ6HX9IJQ55y/OXcT1My1j7NyFIh/nrYR8Vdnt2eq6tMcBoUniIyPE8XpPmQZuwk1D85jwRjQY/93DEfKo0TJw989YqHOHy9QIUODGg/k+n9VmgBPf35SfQtMOyBFOHScEcXkQip08EsZyrU/sea/q3E5ytBO82AIVlJy6RkFh7gCoSmg6/SrpC38wkXQwMOQFb0fxvbtyI9u9U5EW8cg/Z8ftU0+o=
deploy:
  provider: s3
  access_key_id: AKIAIP5UVN77EFW7SUYA
  secret_access_key:
    secure: EV6BVRH1pj7vfIUmRiCZk4KNo8Lh5nrNuES2ppkOoxtjDT4LKuIyn7Q95UZhTEPZ+sTHk18ogtiDE6+MAxvTR3SG3NB4viGuLT4++Y2fk5FlotItSoPqr0nLJUooFUJoBS65hB2SKV4TpdE7ijVZQxPZEXBpJoffb7CXhEZunO5GPMdK2kjHSeSmhn5/sKx7i4hsVcKwAvp2w+4ElukA4lwD5cLVhXMQDj44uLHG9U60nFgYhou7OsGV5CN9nY1Wa1IH0l+0gzgiuAtLScOhYVRrfAoosc567kKRMN5YG95F2wgYNfIrkxH3nDh2JDDIIADYV7Jqn36Wg2wROPFUVs9V887ckHE0X49979cnGRFLh3iPEbYyMUFWFQrRGEaZ/wBA944YPMtCX1hVAe+/0M1xUtD+NMHZ5gYi04ISo76063zUr39PtxSEQD7VSQ5DFjtXF6E0UcXRMLeN1VI7tPXB28CmbynJ2lrgivVnLxjsNIS39o+2m7u0e5x9r7v+viXPIN4iX8j/RuyRGk9/Hd79Gi0Uyt7C2EKF3ZYMZXAXVkhRUMid6pfVJC1hjhcEQtlk3uZBj+/9zvUMtwx4CVGZpNiRpj6sh/ghSMoOPh+TEgsE3L+eoavRO5B9YeIcS4AT/R6pMEX0IjbAYveZopc+SFX7F8iZEMk0X+pPYo4=
  bucket: old-fashioned
  local-dir: dist
  acl: public_read
  skip_cleanup: true
  on:
    repo: myles/old-fashioned
notifications:
  slack:
    secure: Q5nefokLbkl9OnXyOfg4ZFrh3Xmy+zk4HVHYFrNvE2T+MDDPeBGK79xqr+/fOYrzHF64i5rHhwaUl2cPeFWrtoJ5TbmlOvx4SUXinM7rooejZO5cL4RozIo88/JhsTs1K8VY7JisN/uw61zMSQf+2dfhZb887AsaKqHQRmOH/0SMoMCEKrAKOvwAHGad1VKQL8O81vnjFJqlT3skFgDzbf8V2Rg3Gx9mKJMOHCq05s44xNxIonjIO3jrMqQ9LZxPjKsYRcUqw/kQ6t2gtKPRa65X6lfCFbJ7N9A5is42h7K1ZJ/HSVQVMAvR1GhMjJKRiAmgK/3RUic75GJPS8pwQVVXOD3kVz4hzckepmaqyE4sprSO8+9wCa1zSAy5sEf2FXE3QYD7x/Lljc2truL/HPQUvehL8I1OqqAC3W7q2vmoZeS0HlxDY/4q81Sw5EaxoR3r/5h39JGKKxcIRudWfFmFQpFCyxG9Vg90YbKXY0T3O59cNVCUZnZGFEQx+cpybJY69bGP4M5mkOduwYAMqgqBw3/ff8NPlCvz24yUKLVz8++Ve5V0fvA+mDBG6FdpQoxdDoTEWTEUWmHG/cBt1+BxKPTTK/JxBo+10cGl0epKxSHMH4095IyqgGatiIKElFy3w4zWfu68FYf6U473hKVwNegsAjoZ680kkqF2UTA=
