language: node_js
node_js:
- '0.10'
before_install: bundle install
before_script:
- npm install -g bower grunt-cli
- npm install
- bower install
script:
- grunt test
- grunt build
after_success:
- grunt docs:deploy:travis
before_deploy:
- grunt build
env:
  global:
    secure: GHo9ZJMLP2CvyuL5OktQINfBzNgFJJar+4t1HSuiPAlgecn1s0pCEFBaYo3Tuw9WGJkbeftFK5V1q7ftUHuXHbehH49eSwI74SSiSY+YEqC/BxBfQIlCvfzjYFrTKzN5G8Jj4IjZ9llAFx2C/CWxMdr61ahFJnX/tywddG1cbZIiVCDNjiu6IuTUu2R/BbyMZSahY6wZYf+YbP83XVy+4Q8mkozzQfel6qL1fpRsJCnyW7emIJwUmp5y0962coD6Gbo7BsvdJllcPa1nJ4J6EUtkZSCpX51xJZafJeh7iLDHpMcqdC5wlih4nO6xC7Mxvk+k1+ddCU6gcEP09K5RsJP4qH3nt+rrKDjL60EzoMTE94v4t0bKinoZm6Z0NsZzpfT0dH69fAOBPZI457Qq9sSn++AZZMyjQfxD/DOS7M7DPnia52RZXUmj6wqw3UojPIECUtjT+06LZkZ6HX9IJQ55y/OXcT1My1j7NyFIh/nrYR8Vdnt2eq6tMcBoUniIyPE8XpPmQZuwk1D85jwRjQY/93DEfKo0TJw989YqHOHy9QIUODGg/k+n9VmgBPf35SfQtMOyBFOHScEcXkQip08EsZyrU/sea/q3E5ytBO82AIVlJy6RkFh7gCoSmg6/SrpC38wkXQwMOQFb0fxvbtyI9u9U5EW8cg/Z8ftU0+o=
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJHANIGDTMCK63J7Q
  secret_access_key:
    secure: Dt2FKmxt87UtIKlkJtnFblPGqdodpoUuBq72HescFA2UAjMoBdZpBK0sV9Pur9Tny1UnCgWzgF1szint5MSnp+wN2c+jRto3fHGVkKTWNH77s2XLeC4b37w94hQ5UtsybV++pa/n7srvDeFD1DdAKeuLMJU008/M+WdAR1PHg9TQyf5gIjBVv/64hWiFmS01sbdoT9C9xDLVTwCr/8TayJcWtcYHmQju2lCi/DoRYfAXsbUY42UwkxZfS18ss/0zgbjXA6HhFiLzh9DUCjS8W8sDnMhqA46ZarU5aqoknKeTQBo8GFvoTQdioll0XzNRUYoTyt3JCC+tTN7T/rCuq+jXfGx4SbgIjZ+GnZHIuqRiO0KMCWMs9S0EVg+8sC5PE+qZOjmRaXQr0XK65ntOvDr1BLTMmllSL/kSzb/M/g/bJfT2ArOxBcry2gTPiY8gVmR0MoWZGXsVp4sFYdsIyB1krNcvKEP+DpMU2iqKrlrsdn4YpWvO5Vw+Jshkxn59/S0fYJjktaQeTZlgSHIBO5GsLS2NMfMmtT9hxmfYVoCRLlrBvSDOA7Yjf9/QIiTcOvixsN4Te621YKKV1WIufMUO63bFYxoSGy4oYwNA0Vnesm6Arltb3sc82NxSjKFxStJNvAv7CUgH5QAgoiRs4RM3x8bwMt9M/Xoqmv3n4qY=
  bucket: old-fashioned
  local-dir: dist
  acl: public_read
  on:
    repo: myles/old-fashioned
