language: node_js
node_js:
- '0.10'
before_install: bundle install
before_script:
- npm install -g bower grunt-cli
- npm install
- bower install
script:
- grunt test
- grunt build
after_success:
- grunt docs:deploy:travis
env:
  global:
    secure: GHo9ZJMLP2CvyuL5OktQINfBzNgFJJar+4t1HSuiPAlgecn1s0pCEFBaYo3Tuw9WGJkbeftFK5V1q7ftUHuXHbehH49eSwI74SSiSY+YEqC/BxBfQIlCvfzjYFrTKzN5G8Jj4IjZ9llAFx2C/CWxMdr61ahFJnX/tywddG1cbZIiVCDNjiu6IuTUu2R/BbyMZSahY6wZYf+YbP83XVy+4Q8mkozzQfel6qL1fpRsJCnyW7emIJwUmp5y0962coD6Gbo7BsvdJllcPa1nJ4J6EUtkZSCpX51xJZafJeh7iLDHpMcqdC5wlih4nO6xC7Mxvk+k1+ddCU6gcEP09K5RsJP4qH3nt+rrKDjL60EzoMTE94v4t0bKinoZm6Z0NsZzpfT0dH69fAOBPZI457Qq9sSn++AZZMyjQfxD/DOS7M7DPnia52RZXUmj6wqw3UojPIECUtjT+06LZkZ6HX9IJQ55y/OXcT1My1j7NyFIh/nrYR8Vdnt2eq6tMcBoUniIyPE8XpPmQZuwk1D85jwRjQY/93DEfKo0TJw989YqHOHy9QIUODGg/k+n9VmgBPf35SfQtMOyBFOHScEcXkQip08EsZyrU/sea/q3E5ytBO82AIVlJy6RkFh7gCoSmg6/SrpC38wkXQwMOQFb0fxvbtyI9u9U5EW8cg/Z8ftU0+o=
